import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {["/", "/immerjs"].map((routeHref) => (
        <Link className=" mr-6 px-8 bg-pink-200 hover:bg-pink-100" key={routeHref} href={routeHref}>
          {routeHref}
        </Link>
      ))}
      <main className="border-2 border-blue-200">
        {children}
      </main>
      </body>
    </html>
  );
}
